### ISSUE TITLE
New config option

### ISSUE THREAD

**Issue by firyy** [ZsoltMolnarrr/Rolling#25]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

Simple but powerful - configuration for the combat roll to be initially locked and players would need a book to learn it or an enchantment to unlock it.

Thanks for the mod :)

**Comment by togera13** [comment]
I imagine this would be fixed if they just let you change the starting rolls, so you could change it to 0 & the player would have to use the mod's enchantments to be able to roll.

I also want this since I'd like to be able to restrict the rolls or increase the starting rolls.
(I am using Forge Combat Roll 1.1.5-1.19.2.)

**Comment by ZsoltMolnarrr** [comment]
After careful consideration, I am sorry I need to reject this idea.
In order for this to work additional UI would need to be developed, which I really don't want to deal with during the maintenance of this project.

Setting the default attribute value of  `combatroll:count` attribute to zero is already possible.
Other mods (such as quest mods) or server side scripts can be used to unlock the roll ability by setting its initial value to 1.
