### ISSUE TITLE
(Request) Air Roll distance adjustment / max  air rolls config options.

### ISSUE THREAD

**Issue by togera13** [ZsoltMolnarrr/Rolling#30]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES
**Is your feature request related to a problem? Please describe.**
I just think it would be neat if we could adjust the ground rolling & adjust air rolling distance.  (The config says we can only ADD ground rolling distance.)

**Describe the solution you'd like**
An option to change the roll distance in blocks or whatever would be easiest, being able to use the roll midair to try and clear a gap is a fun concept, but I feel it may be too powerful in terms of how much distance it can clear by default. (Also, I have not tested it yet, but if you can do multiple rolls in the air, then an option to change the max air rolls would also be appreciated.)

**Describe alternatives you've considered**
Adjusting roll distance, but the config only seems to allow adding roll distance, though adjusting both ground & air rolling distance separately would be ideal.

**Additional context**
I am using forge Combat Roll 1.1.5 (1.19.2)

**Comment by ZsoltMolnarrr** [comment]
Rolling midair is disabled by default for good reason.
Roll distance attribute was adjusted based on heuristic data. AFAIK there is no way to make a configurable for you are looking for.

Closing the ticket since, I have no clue how to implement this.
Feel free to send a pullrequest if you figure it out.

Also please note 1.19.2 versions are no longer being developed.
