### ISSUE TITLE
[Feature Request] Allow Some Actions to Happen Out of a Roll, to Allow Smoother Transitions for Traversial

### ISSUE THREAD

**Issue by Justfines** [ZsoltMolnarrr/Rolling#5]
**I read project readme, checked client side and server side configurations, and no such feature exists**- YES

Currently, while very powerful, the combat roll has a decent bit of ending lag. This is a good balancing method, but also makes it feel stiff for usage as a movement tool

**Describe the solution you'd like**
I would like some method to maintain some of the momentum of the roll, like the ability to jump out of the end of a roll (if still on the ground), with the jump having the horizontal speed (and potentially a lower amount of vertical distance on the jump). Preferably it would involve good timing to actually handle the jump and not able to be abuse with just holding the jump button. In addition to the small time-frame to do this, it could possibly modify the current cooldown recharge rate to be moderately slower after a roll-jump, Making it most tactical to use, and emphasizing the bonuses of the enchantments more.

**Describe alternatives you've considered**
Other ways to possibly balance this is by forcing this ability to be on an enchantment only, limiting the rarity (and allowing it to be mutually exclusive with other enchantments like cool down speed).

Other alternatives I thought of to help it feel like a good all-around mobility tool: maybe just shortening the small delay after the roll (for specific actions like jumping or when its interrupted like rolling into a wall, etc), but not giving those actions any special treatment (especially when rolling into a wall, where the distance is reduced anyways), or allowing a well timed roll to reduce fall damage some amount  (a minuscule reduction), and gain bonus distance

**Additional context**
I like good mobility options that feel smooth and rewarding (even if they are not actually rewarding), and was a fan of smart moving when that was still updated, and overall good platformer-esque movement when possible, as it can be very satisfying learning and mastering the techniques. The combat roll asis is there as one of these techniques, but has smaller things that I believe could make it feel more dynamic with how to use it in other ways.

**Comment by ZsoltMolnarrr** [comment]
So currently roll has a flat, static duration of 10 ticks, during that the player cannot attack/itemuse/jump.
I can make this configurable, so you can set any number in your modpack/installation.

What do you think about this solution?

**Comment by Justfines** [comment]
I think that could also work as a good configuration option. It would also allow others that would rather nerf it in that way the option to do so too.  That's a good solid solution

**Comment by ZsoltMolnarrr** [comment]
Please join my discord to get a testable version of this change. https://discord.gg/KN9b3pjFTM
Ping me please.

**Comment by redactedscribe** [comment]
Hello @ZsoltMolnarrr, was this ever implemented? Ah, I see it now `"allow_jump_while_rolling": false`. Shame it supposedly breaks something by being enabled. Do you think you would ever iterate further on this idea?

Just leaving my thoughts written before finding the option above:

I think it would be pretty neat to be able to jump out of a combat roll too. How I imagine it working is that since rolling increases your speed, rolling then triggering a jump (within a short window of time, like 400ms, and if still on the ground) would let you jump in the given direction at that speed (perhaps even boosted a little as if pushing off with your legs).

This would let you bridge gaps you otherwise couldn't with a roll alone. For example: A roll of `combatroll:distance` (3) blocks + a jump of (`combatroll:distance` (3) + `combatroll:jumpdistance` (1)) blocks. A jump after roll would be at minimum the same length as a roll + 1. This would ideally work in all directions, however it could be configured so that if rolling backwards and then jumping (typically in combat), to limit the jump to a single block for it to have an effect, but not so much that you leave the battlefield).

Finally, invulnerability should only affect the roll, not the jump (not sure if that's the case currently).

---

Seeing as we can jump out of a roll, I guess the only request is to make it not break what it does. Being able to jump out of the roll really adds to the experience I find. It would ideally be the default.
